// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMryhAhVfYSgyVl24OxCSgaRAfKFBkeD0',
    appId: '1:946049116093:web:3d1d5e6904398af31d14d4',
    messagingSenderId: '946049116093',
    projectId: 'salinsalita-390a5',
    authDomain: 'salinsalita-390a5.firebaseapp.com',
    storageBucket: 'salinsalita-390a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5iFJz5A_WOmpOPBdniQR0m2CkXUA3DU',
    appId: '1:946049116093:android:00d38d6aab96aae81d14d4',
    messagingSenderId: '946049116093',
    projectId: 'salinsalita-390a5',
    storageBucket: 'salinsalita-390a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7FGMRnXPZpeMlqwbRC2AV3Op-UHLeWvc',
    appId: '1:946049116093:ios:f21d39f57ee41bbe1d14d4',
    messagingSenderId: '946049116093',
    projectId: 'salinsalita-390a5',
    storageBucket: 'salinsalita-390a5.appspot.com',
    iosBundleId: 'com.example.salinsalita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7FGMRnXPZpeMlqwbRC2AV3Op-UHLeWvc',
    appId: '1:946049116093:ios:f21d39f57ee41bbe1d14d4',
    messagingSenderId: '946049116093',
    projectId: 'salinsalita-390a5',
    storageBucket: 'salinsalita-390a5.appspot.com',
    iosBundleId: 'com.example.salinsalita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMryhAhVfYSgyVl24OxCSgaRAfKFBkeD0',
    appId: '1:946049116093:web:85bc664e946cfcca1d14d4',
    messagingSenderId: '946049116093',
    projectId: 'salinsalita-390a5',
    authDomain: 'salinsalita-390a5.firebaseapp.com',
    storageBucket: 'salinsalita-390a5.appspot.com',
  );
}
